### ISSUE TITLE
Remove use of Promise.defer()

### ISSUE THREAD

**Issue by jonnyt886** [rogierschouten/async-lock#17]
Running this on Node v10 gives:

    (node:28588) Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.

I see that some Promise usage was cleared up in #2, but I think the code needs to remove all use of `Promise.defer()` in favour of `new Promise(...)`.

**Comment by rogierschouten** [comment]
@jonnyt886  Good point.  

I'm only passively maintaining this module since the original owner quit, and I'm no longer using it myself. Would you maybe have the time to put in a PR?

**Comment by jtyers** [comment]
@rogierschouten Sure, I'll get a PR ready.

**Comment by amarzavery** [comment]
The library is doing a conditional check to find out if defer exists and is of type `function` then it uses that. It does not use it by default. It is simply providing compatibility with `Q` library. If the consumer of async-lock stops using `Q` library for Promises then node.js should not emit that warning.

Am I missing something?

**Comment by jtyers** [comment]
@amarzavery you're right. I use `bluebird`, and bluebird provides a `defer` method for backwards compatibility, which then gets picked up and called by `async-lock`. Since `defer` is deprecated, we simply should refactor the code so that it doesn't use `defer` but uses the accepted way of doing things.

**Comment by jtyers** [comment]
@rogierschouten PR ready, sorry for the slowness!

**Comment by rogierschouten** [comment]
@jtyers thx!  I just remembered the reason for not using the Promise constructor though: in one of the promise libraries (I think Q), the constructor callback was not called synchronously. This broke the lib. Detecting the defer method was like detecting the Q library.  I'm currently on holiday, can you check if Q constructor is synchrous by now? Otherwise we may need to devise another way of detecting Q so we can use it's defer method.

**Comment by jtyers** [comment]
Righto, I'll take a look into that when I get some time.

**Comment by rogierschouten** [comment]
@jtyers in fact it may be best to detect whether the promise library has a properly working constructor (i.e. synchrous) and act on that, and only check for the presence of defer() when the constructor is a-sync
