### ISSUE TITLE
process not set when acquiring lock

### ISSUE THREAD

**Issue by kvandelden** [rogierschouten/async-lock#37]
Not sure what has changed in chrome, but we are now getting a process undefined error from this package.

![image](https://user-images.githubusercontent.com/17126950/98295421-2fe46a80-1f77-11eb-8b47-fe31594cf869.png)

updated this line to avoid the error..

and subsequently received the same error on.
![image](https://user-images.githubusercontent.com/17126950/98295494-47bbee80-1f77-11eb-8d7e-d0f7aa2446ad.png)

**Comment by rogierschouten** [comment]
@kvandelden thank you for reporting. As you can see in the readme, I only merge PRs for this package, as I am not the original owner and I'm not using it myself. Any chance of getting a fix in ?

**Comment by sr258** [comment]
Have you updated to Webpack 5 by any chance? Webpack 5 doesn't contain the polyfill to add process to the bundle by default anymore. That's why process is undefined (it doesn't exist in the browser). 

This is what happened in a new project I set up with Webpack 5. Older ones with Webpack 4 don't have this issue.

**Comment by Philipp91** [comment]
https://sanchit3b.medium.com/how-to-polyfill-node-core-modules-in-webpack-5-905c1f5504a0

**Comment by Philipp91** [comment]
The [domain feature is deprecated](https://nodejs.org/api/domain.html#domain_domain) in nodejs, see also [here](https://stackoverflow.com/a/38882514/636372). IIUC it's referenced in async-lock to provide the feature of ["domain-reentrant locks"](https://github.com/rogierschouten/async-lock/commit/b45cdf69d7ec6b5cacc2357bb83256a1be76860b). As long as the domain feature exists in nodejs, there's a chance that someone wants domain-reentrant locks. And since there's a polyfill for browsers, one could even use them there (not sure if they work there, but let's assume so). In both cases, the polyfill would be loaded by the application code. So async-lock only needs to move on gracefully when the `process` isn't present, and perhaps throw an error if someone requests domain-reentrant locks then. I can send a PR.

**Comment by rogierschouten** [comment]
Closed through #42 and released as v1.2.7
