### ISSUE TITLE
Unexpected: batch keys get reversed

### ISSUE THREAD

**Issue by taschmidt** [rogierschouten/async-lock#53]
Is there a reason why the acquireBatch function reverses the keys [here](https://github.com/rogierschouten/async-lock/blob/955597cfc5118d486d5451710cce3885ec447b01/lib/index.js#L235)? The problem is Array.prototype.reverse is a destructive function that (unexpectedly) modifies the original array. I had a downstream bug that I just tracked back to this behavior.

At the very least, could the line above be changed to something like `[...keys].reverse()` or something? And yes, I know I can work around this behavior by doing the same up in my code but this behavior doesn't seem desirable.

**Comment by rogierschouten** [comment]
@taschmidt  honestly I have no idea.  I just took over this module from a guy who was not maintaining it anymore, in order to fix a bug of my own.    I think the code and the tests are low quality and I don't understand half of it.  I no longer use this package myself. 

For this reason, I don't change the code, I just merge PRs.  My only rule is that any PR has to be accompanied by unit tests, as this is a widely-used package. 

So please feel free to come with a well-tested PR and I will be happy to merge and publish it.

**Comment by simeonborko** [comment]
The `keys` array is reversed so that keys are acquired in the correct order. After the first key is acquired, its function is to acquire the next key, and the function for the last key is `fn`. See comment above the `_acquireBatch`.

@taschmidt , creating a copy of `keys`, as you propose, is a good way from my point of view.

**Comment by taschmidt** [comment]
Awesome, thanks! How often do you guys do releases?

**Comment by rogierschouten** [comment]
Your change is already published. Thank you for the PR!
